package GUI;

import java.util.ArrayList;
import java.util.List;

import javax.print.attribute.standard.JobHoldUntil;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Classes.*;
import java.net.URL;

/**
 * @author Kris
 */
public class Main extends javax.swing.JFrame {

	ArrayList agendaDir = new ArrayList();
                  String rootDir = System.getProperty("user.dir");
                  String agendaIcon = rootDir + "/Agenda.jar/Assets/Images/agenda.png";

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();
		CreateModel();
                    URL imageURL = Main.class.getResource("/Assets/Images/agenda.png");
                                if (imageURL != null) {
                                    // Convertir el URL a una cadena que `RSScaleLabel` puede entender.
                                    String imagePath = imageURL.toString();
                                    System.out.println(imagePath);
                                    rsscalelabel.RSScaleLabel.setScaleLabel(lblimg_agenda, imagePath);
                                } else {
                                    System.err.println("No se pudo encontrar la imagen: /Assets/Images/agenda.png");
                                }
                            }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainContainer = new javax.swing.JPanel();
        QueryContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lblimg_agenda = new javax.swing.JLabel();
        ContentContainer = new javax.swing.JPanel();
        btn_seeData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_contacts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setMinimumSize(new java.awt.Dimension(854, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainContainer.setBackground(java.awt.Color.blue);
        MainContainer.setPreferredSize(new java.awt.Dimension(1200, 720));

        QueryContainer.setBackground(java.awt.Color.darkGray);
        QueryContainer.setPreferredSize(new java.awt.Dimension(200, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Agenda personal");

        jLabel2.setText("Identificacion:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Dirección:");

        btn_save.setText("Guardar");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });

        btn_clear.setText("Limpiar");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        lblimg_agenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout QueryContainerLayout = new javax.swing.GroupLayout(QueryContainer);
        QueryContainer.setLayout(QueryContainerLayout);
        QueryContainerLayout.setHorizontalGroup(
            QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryContainerLayout.createSequentialGroup()
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QueryContainerLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(QueryContainerLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(QueryContainerLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(QueryContainerLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(QueryContainerLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(QueryContainerLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblimg_agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)))
                    .addGroup(QueryContainerLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        QueryContainerLayout.setVerticalGroup(
            QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryContainerLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear))
                .addGap(43, 43, 43)
                .addComponent(lblimg_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btn_seeData.setText("Ver datos de agenda");
        btn_seeData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seeDataMouseClicked(evt);
            }
        });

        table_contacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombre", "Apellido", "Telefono", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_contacts);

        javax.swing.GroupLayout ContentContainerLayout = new javax.swing.GroupLayout(ContentContainer);
        ContentContainer.setLayout(ContentContainerLayout);
        ContentContainerLayout.setHorizontalGroup(
            ContentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addGroup(ContentContainerLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_seeData)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContentContainerLayout.setVerticalGroup(
            ContentContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentContainerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_seeData)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainContainerLayout = new javax.swing.GroupLayout(MainContainer);
        MainContainer.setLayout(MainContainerLayout);
        MainContainerLayout.setHorizontalGroup(
            MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainContainerLayout.createSequentialGroup()
                .addComponent(QueryContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ContentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainContainerLayout.setVerticalGroup(
            MainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QueryContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(ContentContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(MainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_saveMouseClicked

		String id = txt_id.getText();
		String name = txt_name.getText();
		String surname = txt_surname.getText();
		String phoneNumber = txt_phoneNumber.getText();
		String address = txt_address.getText();

		String fields[] = { id, name, surname, phoneNumber, address };

		int fieldCheckout = 0;
		Boolean isDuplicated = false;

		for (String field : fields) {
			if (!field.isEmpty()) {
				fieldCheckout++;
			}
		}

		if (fieldCheckout == 5) {

			List<Contact> contacts = JSONReader.GetContacts();
			for (Contact contact : contacts) {
				// System.out.println("JSON id: " + contact.getId() + " txt id: " + id + " duplicated: " + isDuplicated);

				if (id.equals(contact.getId())) {
					JOptionPane.showMessageDialog(this,
							"la identificación " + id + " ya está registrada como contacto.", "ERROR",
							JOptionPane.ERROR_MESSAGE);
					isDuplicated = true;
					break;
				}
				else {
					isDuplicated = false;
				}

			}

			if (!isDuplicated) {
				JSONReader.CreateNewContact(id, name, surname, phoneNumber, address);
				Contact newContact = new Contact(id, name, surname, phoneNumber, address);
				contacts.add(newContact);
				JSONReader.SaveContacts(contacts);

				txt_id.setText("");
				txt_name.setText("");
				txt_surname.setText("");
				txt_phoneNumber.setText("");
				txt_address.setText("");
	
				txt_id.requestFocusInWindow();

				JOptionPane.showMessageDialog(this, "El contacto ha sido creado", "Información",JOptionPane.INFORMATION_MESSAGE);
			}



			

		} else {
			JOptionPane.showMessageDialog(this, "No pueden haber campos vacios en el formulario", "Atención",
					JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_btn_saveMouseClicked

	private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_clearMouseClicked
		txt_id.setText("");
		txt_name.setText("");
		txt_surname.setText("");
		txt_phoneNumber.setText("");
		txt_address.setText("");

		txt_id.requestFocusInWindow();
	}// GEN-LAST:event_btn_clearMouseClicked

	private void btn_seeDataMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_seeDataMouseClicked

		List<Contact> contacts = JSONReader.GetContacts();

		// clear data in table
		model.setRowCount(0);

		if (!contacts.isEmpty()) {
			for (Contact contact : contacts) {
				model.addRow(new Object[] {
						contact.getId(),
						contact.getName(),
						contact.getSurname(),
						contact.getPhoneNumber(),
						contact.getAddress() });
			}
		} else {
			JOptionPane.showMessageDialog(this, "La agenda está vacia", getTitle(), JOptionPane.INFORMATION_MESSAGE);
		}

	}// GEN-LAST:event_btn_seeDataMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	// JTable model
	DefaultTableModel model;

	private void CreateModel() {
		try {
			model = new DefaultTableModel(null, new String[] {
					"Identificación",
					"Nombres",
					"Apellidos",
					"Telefono",
					"Dirección"
			}) {
				Class[] types = new Class[] {
						java.lang.String.class,
						java.lang.String.class,
						java.lang.String.class,
						java.lang.String.class,
						java.lang.String.class
				};
				boolean[] canEdit = new boolean[] {
						false,
						false,
						false,
						false,
						false
				};

				@Override
				public Class getColumnClass(int columnIndex) {
					return types[columnIndex];
				}

				@Override
				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit[columnIndex];
				}
			};
			table_contacts.setModel(model);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e, getTitle(), JOptionPane.ERROR_MESSAGE);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentContainer;
    private javax.swing.JPanel MainContainer;
    private javax.swing.JPanel QueryContainer;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_seeData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimg_agenda;
    private javax.swing.JTable table_contacts;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}